/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: b208dd4a0895371a782f4434e596679f)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "CompanionAgent" | "CaregiverAgent";
	}
	interface Env {
		AI: Ai;
		KIMI_API_KEY: string;
		CompanionAgent: DurableObjectNamespace /* CompanionAgent */;
		CaregiverAgent: DurableObjectNamespace /* CaregiverAgent */;
	}
}
interface Env extends Cloudflare.Env {}
